Some new changes
henrik-andreasson/syscheck pull request #90
Opened 2021-02-22 09:33 UTC by falleri

2021-02-22 17:01 UTC, henrik-andreasson requested changes
split it up in one pr per feature, eg sc_40 mariabackup and please remove the rpm-qa line

2021-02-23 08:41 UTC, henrik-andreasson approved these changes

2021-02-23 08:42 UTC, henrik-andreasson requested changes
remove rpm row

2021-02-23 08:43 UTC, henrik-andreasson commented on lang/939.english
> +CLEANBAK_DESCR_1="Truncate index run successfully"
update names

2021-02-23 08:43 UTC, henrik-andreasson requested changes
update names this it not clean backups

2021-02-23 08:44 UTC, henrik-andreasson approved these changes

2021-02-23 08:45 UTC, henrik-andreasson approved these changes

2021-02-25 07:25 UTC, falleri commented on lang/939.english
> +CLEANBAK_DESCR_1="Truncate index run successfully"
have update this

2021-03-01 09:20 UTC, falleri commented
need to know if I need to do any more.

2021-03-02 20:46 UTC, henrik-andreasson approved these changes

2021-03-02 20:52 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +fileList=$( cat /tmp/file.txt )
use mktemp

2021-03-02 20:53 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +#select fileName in `cat ${DATAFILE} |cut -f3 -d"="| sort |uniq`; do
remove comments if the code is done

2021-03-02 20:54 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +        #select CA in `egrep "${fileName}" ${DATAFILE}|sort`;do
remove commented code

2021-03-02 20:54 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +  #backupdir=$(mariabackup_full_backup "${MARIABACKUP_DIR}")
remove commented code

2021-03-02 20:54 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +  #if [ -d ${MARIABACKUP_BASEDIR}/${DATESTR}/FULL ];then
remove commented code

2021-03-02 20:54 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +  #if [ -d ${MARIABACKUP_BASEDIR}/${DATESTR}/FULL ];then
remove commented code

2021-03-02 20:55 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> + #    echo "mariabackup_incremental_backup ${BASEBCK} ${MARIABACKUP_DIR}"
remove commented code

2021-03-02 20:56 UTC, henrik-andreasson commented on lang/938.english
> +DESCR[4]="Incrementel backup ok"
spelling

2021-03-02 20:56 UTC, henrik-andreasson commented on lang/938.english
> +DESCR[5]="Desc 5"
???

2021-03-02 20:57 UTC, henrik-andreasson commented on lang/938.english
> +DESCR[6]="Desc 6"
bad desc

2021-03-02 20:57 UTC, henrik-andreasson commented on lang/938.english
> +DESCR[7]="Desc 7"
bad desc

2021-03-02 20:57 UTC, henrik-andreasson commented on lang/938.english
> +DESCR[8]="(%s)"
?

2021-03-02 20:58 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> + echo "WRONG value, bale out"
bale? -> exiting

2021-03-02 20:59 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +elif [ "${PREP_TYPE}" == "CUM" ] ; then
use another word

2021-03-02 21:00 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> + echo "Prepere Incremetel backup  ${PREP_PATH} for restore,,"
spelling incremental

2021-03-02 21:00 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +    #    printlogmess -n ${SCRIPTNAME} -i ${SCRIPTID} -x ${SCRIPTINDEX} -l $INFO  -e ${ERRNO[18]} -d "${DESCR[18]}" -1 "${FULL_BACKUP_DIR}" -2 $TIMETOCOMPLEATE2
remove commented code if done

2021-03-02 21:02 UTC, henrik-andreasson commented on related-available/938_mariabackup.sh
> +fileList=$( cat /tmp/file.txt )
also I do really not like menus in syscheck it is not possible to automate.
can we convert this to a two stage thing? 1. run with --list 2. run with --select

2021-03-02 21:11 UTC, henrik-andreasson approved these changes

2021-03-02 21:11 UTC, henrik-andreasson approved these changes

2021-03-02 21:12 UTC, henrik-andreasson approved these changes

2021-03-02 21:21 UTC, falleri commented
Hi
 it is possible to run -r path_to_recovery_dir_yyyy-mm-dd
It can then be FULL, INC_5 or CUM_3
Is that ok.

Mats

tis 2 mars 2021 kl. 22:02 skrev henrik-andreasson <notifications@github.com
>:

> *@henrik-andreasson* commented on this pull request.
> ------------------------------
>
> In related-available/938_mariabackup.sh
> <https://github.com/henrik-andreasson/syscheck/pull/90#discussion_r585906811>
> :
>
> >
> +Sub_Menu(){
> +#cat ${DATAFILE} |cut -f3 -d"="| sort |uniq
> +# Displays a list of valid backup directorys
> +
> +# Set the prompt for the select command
> +PS3="Type a number or 'q' to quit, or press return to main menu: "
> +
> +# Create a list of files to display
> +#fileList=$(stat -c '%n %.19y ' /backup/mariabackup/* )
> +#fileList=$( cat ${DATAFILE} |cut -f3 -d"="| sort |uniq )
> +fileList=$( cat /tmp/file.txt )
>
> also I do really not like menus in syscheck it is not possible to automate.
> can we convert this to a two stage thing? 1. run with --list 2. run with
> --select
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/henrik-andreasson/syscheck/pull/90#discussion_r585906811>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF4C5DOTYUTNOSF2SZVTCH3TBVG7FANCNFSM4YAFDJMA>
> .
>

2021-03-02 21:22 UTC, falleri commented
Oki

tis 2 mars 2021 kl. 22:00 skrev henrik-andreasson <notifications@github.com
>:

> *@henrik-andreasson* commented on this pull request.
> ------------------------------
>
> In related-available/938_mariabackup.sh
> <https://github.com/henrik-andreasson/syscheck/pull/90#discussion_r585905550>
> :
>
> > +
> +if [ "${PREP_TYPE}" == "FULL" ] ; then
> + echo "Prepere Full backup  ${PREP_PATH} for restore,,"
> + mariabackup_prepare_full ${PREP_PATH}
> +elif [ "${PREP_TYPE}" == "CUM" ] ; then
> + PREP_DIR=$(dirname $PREP_PATH)
> + PREP_BASE=${PREP_DIR}/FULL
> + echo "Prepere Cumulative backup  ${PREP_PATH} for restore,,"
> + echo "Use Full backup from ${PREP_BASE}"
> + mariabackup_prepare_full ${PREP_BASE}
> + echo "Continue to prep cumulativ backup: ${PREP_DIR}"
> + mariabackup_prepare_incrementel ${PREP_PATH} ${PREP_BASE}
> +elif [ "${PREP_TYPE}" == "INC" ] ; then
> + PREP_DIR=$(dirname $PREP_PATH)
> + PREP_BASE=${PREP_DIR}/FULL
> + echo "Prepere Incremetel backup  ${PREP_PATH} for restore,,"
>
> spelling incremental
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/henrik-andreasson/syscheck/pull/90#pullrequestreview-602267192>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF4C5DJPPHUGW3NVDQLA27DTBVGW3ANCNFSM4YAFDJMA>
> .
>

2021-03-02 21:25 UTC, falleri commented
Ok
I need to rember what i think short memorial
I fix
Mats

tis 2 mars 2021 kl. 21:54 skrev henrik-andreasson <notifications@github.com
>:

> *@henrik-andreasson* commented on this pull request.
> ------------------------------
>
> In related-available/938_mariabackup.sh
> <https://github.com/henrik-andreasson/syscheck/pull/90#discussion_r585902002>
> :
>
> >  if [ "${ACTION}" == "BACKUP" -a "${TYPE}" == "FULL" ] ; then
> +# Full backup is only  possible once per date eq 2021-01-22
> +  MARIABACKUP_DIR=${MARIABACKUP_BASEDIR}/${DATESTR}/${TYPE}
> +  #backupdir=$(mariabackup_full_backup "${MARIABACKUP_DIR}")
> +  mariabackup_full_backup "${MARIABACKUP_DIR}"
> +
> +elif [  "${ACTION}" == "BACKUP" -a "${TYPE}" == "INC" ]; then
> +# find last fullbackup find dir FULL, if not exist, exit
> +# Need to have one fullbackup to use as base. with date, it is base  for all Incrementel backup
> +# Try first with this day
> +  DATESTR=$(ls -dtr /backup/mariabackup/*/FULL |tail -1 |cut -f4 -d"/")
> +  #if [ -d ${MARIABACKUP_BASEDIR}/${DATESTR}/FULL ];then
>
> remove commented code
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/henrik-andreasson/syscheck/pull/90#pullrequestreview-602262948>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF4C5DI5ALIBJEKHZV7NAELTBVGCBANCNFSM4YAFDJMA>
> .
>

2021-03-03 09:19 UTC, henrik-andreasson commented
ok if we can run restore auto okok

2021-03-06 09:49 UTC, henrik-andreasson commented
updates accepted

2021-03-06 09:49 UTC, merged